GoogleCloudPlatform/vertex-ai-creative-studio

experiments/veo-app/common/metadata.py
experiments/veo-app/common/utils.py
experiments/veo-app/components/side_nav.py
experiments/veo-app/main.py
experiments/veo-app/models/model_setup.py
experiments/veo-app/pages/home.py
experiments/veo-app/pages/portraits.py
experiments/veo-app/pages/styles.py
experiments/veo-app/pages/veo.py
experiments/veo-app/requirements.txt
experiments/veo-app/uv.lock

Adds Motion Portraits example to Veo 2 app
* Portraits - upload a picture and select style presets for motion direction to be added to the resulting video
* adds a new page, portraits
* adds to main, portrait page
* adds to sidenav new menu reference
* Minor changes to metadata
* Adds a utils and refactors from veo
* Adds a new style to accommodate padding
* Updates requirements

Veo 2 app - Motion portraits

---

experiments/veo-app/common/metadata.py
experiments/veo-app/components/pill.py
experiments/veo-app/pages/library.py

Adds multimedia support for library, not just video, audio, and images too

Veo advanced controls library

---

experiments/mcp-genmedia/mcp-genmedia-go/mcp-chirp3-go/chirp3.go
experiments/mcp-genmedia/mcp-genmedia-go/mcp-imagen-go/imagen.go
experiments/mcp-genmedia/mcp-genmedia-go/mcp-lyria-go/lyria.go
experiments/mcp-genmedia/mcp-genmedia-go/mcp-veo-go/veo.go

Context improvements for MCP servers

MCP context improvements

---

experiments/veo-app/Procfile
experiments/veo-app/README.md
experiments/veo-app/common/metadata.py
experiments/veo-app/common/utils.py
experiments/veo-app/components/constants.py
experiments/veo-app/components/imagen/generation_controls.py
experiments/veo-app/config/default.py
experiments/veo-app/config/navigation.json
experiments/veo-app/developers_guide.md
experiments/veo-app/main.py
experiments/veo-app/models/image_models.py
experiments/veo-app/pages/config.py
experiments/veo-app/pages/edit_images.py
experiments/veo-app/pages/lyria.py
experiments/veo-app/pages/portraits.py
experiments/veo-app/pages/veo.py
experiments/veo-app/requirements.txt
experiments/veo-app/state/imagen_state.py
experiments/veo-app/state/state.py
experiments/veo-app/uv.lock

* image editing (a start, hidden)
* user recording via IAP header
* fastapi + mesop hosting changes
* refactoring for consolidation
* dev guide

v.next additions

---

experiments/veo-app/.gitignore
experiments/veo-app/GEMINI.md
experiments/veo-app/pages/about.py
experiments/veo-app/pages/portraits.py

Refactors the dialog component to be theme-aware and handle overflowing content gracefully.
- **Theme Awareness:** The dialog background and shadow now use `me.theme_var` to adapt to the current light or dark theme.
- **Overflow Handling:** Added `overflow_y="auto"` to the dialog style to ensure that long content is scrollable within the dialog instead of overflowing.
- **Style Overrides:** The component now correctly merges a provided `dialog_style` with its defaults, allowing for robust customization of properties like width and height.
These changes fix visual bugs where the dialog was always white and where content would break out of the dialog's bounds.

feat(dialog): Improve dialog component styling and functionality

---

experiments/Imagen_Product_Recontext/README.md
experiments/Imagen_Product_Recontext/evaluation_imagen_product_recontext_at_scale.ipynb
experiments/Imagen_Product_Recontext/requirements.txt
experiments/README.md

- Add `requirements.txt` to simplify dependency installation.
- Update `README.md` to include:
- Corrected notebook filenames.
- Mention of parallel execution options.
- Detailed "Getting Started," "Installation," and "Usage" sections.

feat: Improve documentation and add requirements file

---

.github/CODEOWNERS
experiments/README.md
experiments/VTO/VTOatScale.ipynb

Updates docs to refer to VTO at scale notebook

doc: updates for VTO at scale

---

experiments/veo-app/main.tf

- Fixes #599 terraform invalid operation - template containers list of object issue

fix: corrected reference to container image

---

experiments/veo-app/components/imagen/advanced_controls.py
experiments/veo-app/components/imagen/generation_controls.py
experiments/veo-app/components/imagen/image_output.py
experiments/veo-app/components/imagen/modifier_controls.py
experiments/veo-app/components/styles.py
experiments/veo-app/components/veo/file_uploader.py
experiments/veo-app/pages/gemini_image_generation.py
experiments/veo-app/pages/imagen.py
experiments/veo-app/pages/veo.py

This commit introduces two main improvements: standardized analytics for all generative models and a series of layout adjustments for a more compact and consistent user interface.
Key changes:
- feat(analytics):
- Implements the `track_model_call` context manager across all generative pages (Imagen, Veo, Gemini Image Gen) to provide consistent, centralized logging for model performance and errors.
- refactor(imagen):
- Refactors the advanced controls to use the standard `me.expansion_panel`, simplifying the component's code.
- Centralizes the `_BOX_STYLE` for all Imagen page components, removing code duplication and improving maintainability.
- fix(layout):
- Reduces margins and gaps in the Imagen page components to create a more compact and polished layout.
- Adjusts the spacing on the …

feat(analytics, layout): Standardize analytics and tighten UI layouts

---

experiments/veo-app/main.tf

Add serviceTokenCreator role in support of file download

---

experiments/veo-app/.gitignore
experiments/veo-app/README.md
experiments/veo-app/config/about_content.json
experiments/veo-app/config/default.py
experiments/veo-app/main.py
experiments/veo-app/pages/about.py
experiments/veo-app/pages/config.py

* Adds configuration for per env configs via `APP_ENV` in .env
* Adds version number

feat(config): per env configs

---

experiments/veo-app/config/banana_presets.py
experiments/veo-app/pages/gemini_image_generation.py
experiments/veo-app/requirements.txt
experiments/veo-app/uv.lock

Adds a few Gemini popular presets

V.next/banana presets

---

experiments/veo-app/components/info_dialog/info_dialog.py
experiments/veo-app/requirements.txt
experiments/veo-app/uv.lock

Thank you for your contribution! Please provide a brief description of your changes and ensure you've completed the checklist below.
What does this PR do? Why is it necessary?
Minor refactor

refactor(v.next): update info dialog format

---

experiments/mcp-genmedia/mcp-genmedia-go/go.work.sum
experiments/mcp-genmedia/mcp-genmedia-go/mcp-chirp3-go/go.sum
experiments/mcp-genmedia/mcp-genmedia-go/mcp-gemini-go/go.mod
experiments/mcp-genmedia/mcp-genmedia-go/mcp-gemini-go/go.sum
experiments/mcp-genmedia/mcp-genmedia-go/mcp-gemini-go/main.go
experiments/mcp-genmedia/mcp-genmedia-go/mcp-gemini-go/tts_handlers.go

updates to speech sdk for Gemini TTS
fixes #706

refactor(mcp): updates to speech sdk fixes #706

---

README.md

Updates the README to highlight experiments, remove inconsistencies from /experiments graduation.

doc(refactor): Updates readme

---

README.md
developers_guide.md

Updates README and developer's guide for clarity

doc(update): updates README and dev guide for clarity

---

config/default.py
models/vto.py
requirements.txt
uv.lock

Global check for location added to VTO
**Fixes #821

fix(vto): fixes #821

---

pages/veo.py

Refactors the event handlers for Veo model selection to be more robust and provide a better user experience.
The previous implementation had several issues:
- It did not correctly handle models with discontinuous supported durations (e.g., Veo 3's [4, 6, 8] seconds), causing an invalid state when switching from a model with a continuous range.
- The validation logic was not applied on initial page load when a model was set via a URL query parameter.
- It would unconditionally reset the generation mode to "t2v", disrupting the user's workflow even when the new model supported the current mode.
This commit introduces a centralized helper function, `_update_state_for_new_model`, to address these problems by:
- Prioritizing the `supported_durations` list for validation.
- Conditionally …

fix(veo): Improve model switching logic and state handling

---

README.md

Docs update to remove references to `experiments/veo-app` for application installation.

doc: updates references to main app

---

README.md
components/convert_to_gif_button/convert_to_gif_button.js
components/convert_to_gif_button/convert_to_gif_button.py
components/media_detail_viewer/media_detail_viewer.js
components/veo/video_display.py
main.py
models/video_processing.py
outputs.tf
pages/pixie_compositor.py
pages/portraits.py
state/veo_state.py

Thank you for your contribution! Please provide a brief description of your changes and ensure you've completed the checklist below.
What does this PR do? 
- Adds the ability to convert videos to GIFs to the Library, Veo, and Motion Portraits pages
- Documents how to grant new users access
Why is it necessary?
**Fixes #838

Add GIF conversion to Library, Veo, and Motion Portraits Pages
